buybacks/urls.py
from django.urls import path
from django.conf.urls import url

from . import views


app_name = 'buybacks'

urlpatterns = [
    path('', views.index, name='index'),
    path('setup', views.setup, name='setup'),

    url(
        r'^item_autocomplete/$',
        views.item_autocomplete,
        name='item_autocomplete',
    ),

    path('program_add', views.program_add, name='program_add'),
    path('program_add_2', views.program_add_2, name='program_add_2'),

    url(
        r'^program/(?P<program_pk>[0-9]+)/$',
        views.program,
        name='program',
    ),
    url(
        r'^program/(?P<program_pk>[0-9]+)/remove$',
        views.program_remove,
        name='program_remove',
    ),

    url(
        r'^program/(?P<program_pk>[0-9]+)/calculate$',
        views.program_calculate,
        name='program_calculate',
    ),
    url(
        r'^program/(?P<program_pk>[0-9]+)/notify$',
        views.program_notify,
        name='program_notify',
    ),

    url(
        r'^program/(?P<program_pk>[0-9]+)/add_item$',
        views.program_add_item,
        name='program_add_item',
    ),
    url(
        r'^program/(?P<program_pk>[0-9]+)/add_location$',
        views.program_add_location,
        name='program_add_location',
    ),

    url(
        r'^program/(?P<program_pk>[0-9]+)/remove_item/(?P<item_type_pk>[0-9]+)$',
        views.program_remove_item,
        name='program_remove_item',
    ),
    url(
        r'^program/(?P<program_pk>[0-9]+)/remove_location/(?P<office_pk>[0-9]+)$',
        views.program_remove_location,
        name='program_remove_location',
    ),
]

buybacks/templates/buybacks/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Buybacks" %}{% endblock %}

{% block content %}
    <br />
    {% include 'buybacks/menu.html' %}
    {% block details %}{% endblock %}
{% endblock %}

buybacks/templates/buybacks/index.html
{% extends 'buybacks/base.html' %}
{% load i18n %}
{% load humanize %}

{% block details %}
<div class="table-responsive">
    <table style="width: 100%; margin: auto;" class="table table-striped table-condensed">
        <thead>
            <tr>
                <th style="width: 50%;">{% trans "Buyback Program Name" %}</th>
                <th style="width: 20%;">{% trans "Corporation" %}</th>
                <th class="text-center" style="width: 30%;">{% trans "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for program in programs %}
            <tr>
                <td style="line-height: 35px;">{{ program.name }}</td>
                <td style="line-height: 35px;">{{ program.corporation.corporation }}</td>
                <td class="text-center">
                    <a class="btn btn-success btn-sm" href="{% url 'buybacks:program_calculate' program_pk=program.id %}">
                        Use this program
                    </a>
                    <a class="btn btn-primary btn-sm" href="{% url 'buybacks:program' program_pk=program.id %}">
                        View
                    </a>
                    {% if perms.buybacks.manage_programs %}
                    <a class="btn btn-danger btn-sm" href="{% url 'buybacks:program_remove' program_pk=program.id %}">
                        Delete
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/menu.html
{% load static %}
{% load i18n %}
{% load navactive %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'buybacks:index' %}">{% trans "Buybacks" %}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <!-- <li class="{% navactive request 'buybacks:index' %}">
                    <a href="#">
                        Statistics
                    </a>
                </li> -->
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if perms.freight.manage_programs %}
                    <a class="btn btn-default navbar-btn" href="{% url 'buybacks:program_add' %}">
                        Create Program
                    </a>
                {% endif %}
                {% if perms.freight.setup_retriever %}
                    <a class="btn btn-default navbar-btn" href="{% url 'buybacks:setup' %}">
                        Setup Corp
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

buybacks/templates/buybacks/page.html
{% extends 'buybacks/base.html' %}

{% block details %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">{{ corporation.corporation_name }} ({{ corporation.corporation_ticker }})</h3>
    </div>
    <div class="panel-body" style="min-height: 100px;">
      {% block body %}{% endblock %}
    </div>
</div>
{% endblock %}

buybacks/templates/buybacks/program.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block body %}
<div class="pull-left">
  <h4>{{ program.name }} - Buyback Program</h4>
</div>

{% if perms.buybacks.manage_programs %}
<div class="pull-right">
  <a class="btn btn-sm btn-success" href="{% url 'buybacks:program_add_item' program_pk=program.id %}">
    Add item & price
  </a>
  <a class="btn btn-sm btn-success" href="{% url 'buybacks:program_add_location' program_pk=program.id %}">
    Add location
  </a>
</div>
{% endif %}

<div style="clear: both; padding-top: 20px; display: flex;" class="table-responsive">
  <table style="width: 60%;" class="table table-striped table-condensed">
      <thead>
          <tr>
              <th style="width: 60%;">{% trans "Item Type" %}</th>
              <th class="text-center" style="width: 10%;">{% trans "Brokerage" %}</th>
              <th class="text-center" style="width: 20%;">{% trans "Refined Value" %}</th>
              {% if perms.buybacks.manage_programs %}
              <th style="width: 10%;"></th>
              {% endif %}
          </tr>
      </thead>
      <tbody>
          {% for item in items %}
          <tr>
              <td>{{ item.item_type.name }}</td>
              <td class="text-center">{{ item.brokerage }}%</td>
              <td class="text-center">{{ item.use_refined_value }}</td>
              {% if perms.buybacks.manage_programs %}
              <td class="text-center">
                <a href="{% url 'buybacks:program_remove_item' program_pk=program.id item_type_pk=item.item_type.id %}">delete</a>
              </td>
              {% endif %}
          </tr>
          {% endfor %}
      </tbody>
  </table>

  <table style="width: 35%; margin-left: 20px;" class="table table-striped table-condensed">
    <thead>
        <tr>
            <th style="width: 90%;">{% trans "Location" %}</th>
            {% if perms.buybacks.manage_programs %}
            <th style="width: 10%;"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for location in locations %}
        <tr>
            <td>{{ location.office.location.name }}</td>
            {% if perms.buybacks.manage_programs %}
            <td>
              <a href="{% url 'buybacks:program_remove_location' program_pk=program.id office_pk=location.office.id %}">delete</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/program_add.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block body %}
<form class="form" action="{% url 'buybacks:program_add_2' %}" method="POST">
  {% csrf_token %}
  {{ form|bootstrap }}
  <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/program_add_item.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<form class="form" action="{% url 'buybacks:program_add_item' program_pk=program.id %}" method="POST">
  {% csrf_token %}
  {{ form|bootstrap }}
  <button type="submit" class="btn btn-primary">Add item</button>
</form>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybacks/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybacks/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/program_add_location.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}

{% block body %}
<form class="form" action="{% url 'buybacks:program_add_location' program_pk=program.id %}" method="POST">
  {% csrf_token %}
  {{ form|bootstrap }}
  <button type="submit" class="btn btn-primary">Add location</button>
</form>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybacks/templates/buybacks/program_calculate.html
{% extends 'buybacks/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}
{% load dict %}
{% load number %}

{% block body %}
<h4>{{ program.name }} - Buyback Program</h4>

{% if value|not_empty %}
<div class="table-responsive" style="margin: 20px 0;">
    <p class="text-muted">Based on the contents you have given us, we have calculated them to be of the following value.</p>
    <p class="text-warning">Please click the <strong>Notify</strong> button to let us know you will be sending the contract.</p>

    <table id="value" style="width: 60%; margin: 20px auto;" class="table table-striped table-condensed">
        <tbody>
            {% for item in value %}
            <tr>
                <td data-type-id="{{ typeids|lookup:item }}" style="width: 55%">{{ item }}</td>
                <td style="width: 15%; text-align: right;">{{ data|lookup:item|format_number:0 }}</td>
                <td style="width: 30%; text-align: right;">{{ value|lookup:item|format_number:2 }} ISK</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div style="text-align: center;">
        <p class="text-muted">Total Contract Value: <span class="text-primary" id="total">{{ total|format_number:0 }}</span> ISK</p>
        <button id="notify" data-program-location="{{ program_location.id }}" data-url="{% url 'buybacks:program_notify' program_pk=program.id %}" class="btn btn-warning btn-sm">Notify</button>
    </div>
</div>
{% endif %}

<form class="form" action="{% url 'buybacks:program_calculate' program_pk=program.id %}" method="POST">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button type="submit" class="btn btn-primary">Calculate</button>
  </form>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybacks/js/notify.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}